// Code generated by tilegen. DO NOT EDIT.

// Solver-independent constraint intermediate representation.
package constraint

import "fmt"

// Kind is one of: boolean, integer, string, version.
type Kind string

const (
	KindBoolean Kind = "boolean"
	KindInteger Kind = "integer"
	KindString  Kind = "string"
	KindVersion Kind = "version"
)

// KindValues lists every Kind, in declaration order.
var KindValues = []Kind{KindBoolean, KindInteger, KindString, KindVersion}

// Valid reports whether s is a known Kind.
func (s Kind) Valid() bool {
	switch s {
	case KindBoolean, KindInteger, KindString, KindVersion:
		return true
	}
	return false
}

// ParseKind returns the Kind spelled s, or an error.
func ParseKind(s string) (Kind, error) {
	if v := Kind(s); v.Valid() {
		return v, nil
	}
	return "", fmt.Errorf("unknown Kind %q", s)
}
