// Code generated by tilegen. DO NOT EDIT.

// Parsing and representation of Silt S-expressions.
package sexpr

type Position struct {
	Line   int `json:"line"`
	Column int `json:"column"`
}

type Node struct {
	Value    string   `json:"value"`
	Children []*Node  `json:"children"`
	Pos      Position `json:"pos"`
}
