// Package emit writes the two configuration files Buildroot and kbuild
// consume. Silt compiles nothing; these files are its only output artifact.
package emit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vinodhalaharvi/silt/compose"
	"github.com/vinodhalaharvi/silt/lang"
)

// Defconfig renders a Buildroot defconfig or a Linux .config fragment.
//
// At Rung 2 only stated constraints are emitted; the file is partial and
// olddefconfig completes it. Rung 7 replaces that with a solved total
// assignment, and this function's output does not otherwise change.
func Defconfig(r *compose.Result, sc lang.Scope) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by silt from %s. Do not edit.\n", r.Image.Name)
	fmt.Fprintf(&b, "# Fragments: %s\n", strings.Join(fragmentNames(r.Fragments), " "))

	lines := map[string]string{}
	for _, c := range r.Constraints[sc] {
		if c.Soft {
			continue // soft constraints need MaxSAT; nothing to emit before Rung 7
		}
		if l := line(c); l != "" {
			lines[c.Symbol] = l
		}
	}
	// Opaque values are emitted verbatim: carried, not reasoned about.
	for _, c := range r.Opaque {
		if scopeFor(c.Symbol) == sc {
			lines[c.Symbol] = line(c)
		}
	}
	if sc == lang.Linux && r.Image.Version != "" {
		// custom-version is a Buildroot-side instruction about the kernel; it
		// is recorded here as a comment so the emitted fragment stays pure.
		fmt.Fprintf(&b, "# kernel version requested: %s\n", r.Image.Version)
	}

	keys := make([]string, 0, len(lines))
	for k := range lines {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(lines[k])
		b.WriteByte('\n')
	}
	return b.String()
}

func line(c lang.Constraint) string {
	switch {
	case c.IsValue:
		return fmt.Sprintf("%s=%q", c.Symbol, c.Value)
	case c.AtLeast:
		// The weakest thing satisfying "m or stronger" is m. Choosing between
		// m and y is the solver's job, so before Rung 7 take the weaker.
		return fmt.Sprintf("%s=%s", c.Symbol, c.Want)
	case c.Want == lang.N:
		return fmt.Sprintf("# %s is not set", c.Symbol)
	default:
		return fmt.Sprintf("%s=%s", c.Symbol, c.Want)
	}
}

func scopeFor(sym string) lang.Scope {
	if strings.HasPrefix(sym, "CONFIG_") {
		return lang.Linux
	}
	return lang.Buildroot
}

func fragmentNames(frs []*lang.Fragment) []string {
	out := make([]string, len(frs))
	for i, f := range frs {
		out[i] = f.ID.String()
	}
	return out
}
