// Package emit writes the configuration files Buildroot and each Kconfig tree
// consume: a defconfig, and one config fragment per other tree. Silt compiles nothing; these files are its only output artifact.
package emit

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/vinodhalaharvi/silt/compose"
	"github.com/vinodhalaharvi/silt/kconfig"
	"github.com/vinodhalaharvi/silt/lang"
)

// Trees lists the non-Buildroot trees this composition configures, sorted.
// Each gets its own config file, handed to Buildroot through that tree's
// consumed-by symbol.
func Trees(r *compose.Result) []string {
	var out []string
	for sc, cs := range r.Constraints {
		if sc != lang.Buildroot && hasHard(cs) {
			out = append(out, string(sc))
		}
	}
	sort.Strings(out)
	return out
}

// FileName is the emitted file for a tree: linux.config, busybox.config.
func FileName(tree string) string {
	if tree == string(lang.Buildroot) {
		return "defconfig"
	}
	return tree + ".config"
}

// BuildrootDefconfig renders the Buildroot defconfig, wiring in the other
// trees' files.
//
// paths maps a tree to the absolute path its config was written to. Each tree
// with constraints is routed through the Buildroot symbol its registry entry
// names: BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES for linux,
// BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES for busybox, and so on. Without
// this a tree's half of every fragment is produced and then silently ignored,
// which is exactly the halves-disagreeing problem Silt exists to remove —
// committed by Silt itself. A tree with constraints and no route is an error,
// for the same reason.
func BuildrootDefconfig(r *compose.Result, paths map[string]string) (string, error) {
	return buildrootDefconfig(r, paths, "")
}

// BuildrootDefconfigWithSolution is the same, with the solution hash recorded
// in the header so a built tree can be told apart from a stale one.
func BuildrootDefconfigWithSolution(r *compose.Result, paths map[string]string, hash string) (string, error) {
	return buildrootDefconfig(r, paths, hash)
}

func buildrootDefconfig(r *compose.Result, paths map[string]string, hash string) (string, error) {
	out := Defconfig(r, lang.Buildroot)
	if hash != "" {
		out = strings.Replace(out, "\n", "\n# silt-solution: "+hash+"\n", 1)
	}
	var extra strings.Builder
	if v := r.Image.Version; v != "" {
		fmt.Fprintf(&extra, "BR2_LINUX_KERNEL_CUSTOM_VERSION=y\n")
		fmt.Fprintf(&extra, "BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE=%q\n", v)
	}
	for _, tree := range Trees(r) {
		path, ok := paths[tree]
		if !ok {
			// Not asked to wire this tree in; the caller is emitting one
			// file, not a build.
			continue
		}
		decl, ok := r.Trees[tree]
		if !ok || decl.ConsumedBy == "" {
			return "", fmt.Errorf("tree %s has constraints but no (consumed-by BR2_...) "+
				"symbol to hand its config to Buildroot", tree)
		}
		fmt.Fprintf(&extra, "%s=%q\n", decl.ConsumedBy, path)
	}
	return out + extra.String(), nil
}

func Defconfig(r *compose.Result, sc lang.Scope) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by silt from %s. Do not edit.\n", r.Image.Name)
	fmt.Fprintf(&b, "# Fragments: %s\n", strings.Join(fragmentNames(r.Fragments), " "))

	// The loaded Kconfig tree is Buildroot's; it can only type Buildroot
	// symbols.
	tree := r.Tree()
	if sc != lang.Buildroot {
		tree = nil
	}
	untyped := 0
	lines := map[string]string{}
	emitLine := func(c lang.Constraint) {
		if c.IsValue && tree == nil && numeric.MatchString(c.Value) {
			untyped++
		}
		if l := typedLine(c, tree); l != "" {
			lines[c.Sym.Name] = l
		}
	}
	for _, c := range r.Constraints[sc] {
		if c.Soft {
			continue // soft constraints need MaxSAT; nothing to emit before Rung 7
		}
		emitLine(c)
	}
	// Opaque values are emitted verbatim: carried, not reasoned about.
	for _, c := range r.Opaque {
		if lang.Scope(c.Sym.Tree) == sc {
			emitLine(c)
		}
	}
	if untyped > 0 {
		// Invariant 9: a loss must appear in the output.
		fmt.Fprintf(&b, "# WARNING: %d numeric value(s) written quoted without a tree to type them;\n"+
			"# kbuild ignores a quoted int or hex. Emit with --buildroot.\n", untyped)
	}
	if sc == lang.Linux && r.Image.Version != "" {
		// custom-version is a Buildroot-side instruction about the kernel, so
		// it is a comment here and a real symbol on the Buildroot side.
		fmt.Fprintf(&b, "# kernel version requested: %s\n", r.Image.Version)
	}

	keys := make([]string, 0, len(lines))
	for k := range lines {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(lines[k])
		b.WriteByte('\n')
	}
	return b.String()
}

var numeric = regexp.MustCompile(`^(-?[0-9]+|0[xX][0-9a-fA-F]+)$`)

// typedLine writes int and hex symbols bare. Every value in a fragment is a
// string, and writing BR2_TARGET_ROOTFS_UBI_SUBSIZE="2048" looks right and is
// silently discarded by kbuild, which wants 2048. Found by importing
// at91sam9x5ek_defconfig and diffing the round trip.
func typedLine(c lang.Constraint, tree *kconfig.Tree) string {
	if c.IsValue && tree != nil {
		if s := tree.Symbols[c.Sym.Name]; s != nil && (s.Type == kconfig.Int || s.Type == kconfig.Hex) {
			return fmt.Sprintf("%s=%s", c.Sym.Name, c.Value)
		}
	}
	return line(c)
}

func line(c lang.Constraint) string {
	switch {
	case c.IsValue:
		return fmt.Sprintf("%s=%q", c.Sym.Name, c.Value)
	case c.AtLeast:
		// The weakest thing satisfying "m or stronger" is m. Choosing between
		// m and y is the solver's job, so before Rung 7 take the weaker.
		return fmt.Sprintf("%s=%s", c.Sym.Name, c.Want)
	case c.Want == lang.N:
		return fmt.Sprintf("# %s is not set", c.Sym.Name)
	default:
		return fmt.Sprintf("%s=%s", c.Sym.Name, c.Want)
	}
}

func hasHard(cs []lang.Constraint) bool {
	for _, c := range cs {
		if !c.Soft {
			return true
		}
	}
	return false
}

func fragmentNames(frs []*lang.Fragment) []string {
	out := make([]string, len(frs))
	for i, f := range frs {
		out[i] = f.ID.String()
	}
	return out
}
