// Code generated by tilegen. DO NOT EDIT.

// Resolved build dependency graph.
package dag

type Node struct {
	ID       string   `json:"id"`
	Deps     []string `json:"deps"`
	CPU      int      `json:"cpu"`
	MemoryMB int      `json:"memory_mb"`
}
