obj-$(CONFIG_SERIAL_AMBA_PL011) += amba-pl011.o
# a composite module: the compatible string lives in one part, the symbol
# builds the whole thing
obj-$(CONFIG_SERIAL_SC16IS7XX) += sc16is7xx.o
sc16is7xx-objs := sc16is7xx-core.o sc16is7xx-spi.o
