package kconfig

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// BR2_EXTERNAL is how Buildroot takes packages, board material and
// configuration from a tree that is not itself. The Kconfig files of those
// trees are not sourced directly: Buildroot's Config.in sources
// $BR2_BASE_DIR/.br2-external.in.paths and .br2-external.in.menus, which are
// generated by support/scripts/br2-external from the list of external trees.
//
// So a tree with externals cannot be imported from the checkout alone, which
// is why silt check called every symbol from an external tree unknown. Rather
// than reimplement the generator — its output has grown provides/ hooks for
// toolchains, jpeg, openssl and skeleton, and will grow more — Silt runs
// Buildroot's own script, which is the authority for its own format.

// PrepareExternal generates the .br2-external.in.* files for externals into
// baseDir, and returns the environment additions the importer needs. An empty
// list still generates the files, because Buildroot's Config.in sources them
// unconditionally: without them the import fails on the first source line.
func PrepareExternal(root, baseDir string, externals []string) (map[string]string, error) {
	script := filepath.Join(root, "support", "scripts", "br2-external")
	if _, err := os.Stat(script); err != nil {
		return nil, fmt.Errorf("%s: %w", script, err)
	}
	if err := os.MkdirAll(baseDir, 0o755); err != nil {
		return nil, err
	}
	abs := make([]string, 0, len(externals))
	for _, e := range externals {
		a, err := filepath.Abs(e)
		if err != nil {
			return nil, err
		}
		if _, err := os.Stat(filepath.Join(a, "external.desc")); err != nil {
			return nil, fmt.Errorf("%s is not a br2-external tree: no external.desc", e)
		}
		abs = append(abs, a)
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return nil, err
	}
	cmd := exec.Command(script, append([]string{"-d", absBase}, abs...)...)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("support/scripts/br2-external: %w\n%s", err, out)
	}
	env := map[string]string{"BR2_BASE_DIR": absBase, "BASE_DIR": absBase}

	// The external trees' own Config.in files source their packages through
	// $BR2_EXTERNAL_<NAME>_PATH, which make exports from the generated
	// .br2-external.mk. Without those in the environment the import reads
	// the menus file, follows the source line and finds nothing, which is
	// how BR2_PACKAGE_HELLO_SILT stayed missing from a tree that declares it.
	mk, err := os.ReadFile(filepath.Join(absBase, ".br2-external.mk"))
	if err != nil {
		return nil, err
	}
	for _, line := range strings.Split(string(mk), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "export ") {
			continue
		}
		k, v, ok := strings.Cut(strings.TrimPrefix(line, "export "), "=")
		if !ok {
			continue
		}
		env[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return env, nil
}
