// Package esphome turns silt's constraints into an ESPHome YAML document.
//
// Most appliances here are two computers. A Linux board runs the gateway and
// speaks Modbus, OPC UA and MQTT; a microcontroller on the wall reads the
// sensor or closes the relay. The garage door in this repository is exactly
// that: a Raspberry Pi advertising a route to an ESP32, and an ESP32 running
// ESPHome.
//
// They are configured by two tools, in two files, and the things they must
// agree about are agreed by hand:
//
//	the topic the ESP publishes    and the topic the gateway subscribes to
//	the address the ESP has        and the /32 route the tunnel advertises
//	the protocol each speaks       native API on one side, MQTT on the other
//
// Each of those is one fact written twice, and nothing checks the two copies.
// A device that builds, flashes and boots perfectly on both sides can be
// unable to talk, and the first sign is a dashboard that never updates.
//
// So ESPHome becomes another tree. Silt does not build the firmware - esphome
// does, the way Buildroot builds images - and it does not model the whole of a
// configuration language that gains components monthly. It models the
// interface: the surface where two configurations have to agree, which is
// where the mistakes are.
package esphome

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Doc is a YAML document being assembled from dotted paths.
type Doc struct {
	// values maps a dotted path to its value, in the order sort.Strings puts
	// them, which is the order they are written.
	values map[string]string
}

func New() *Doc { return &Doc{values: map[string]string{}} }

// Set records one path.
func (d *Doc) Set(path, value string) { d.values[path] = value }

// Len is how many paths are set.
func (d *Doc) Len() int { return len(d.values) }

// node is the tree the paths are gathered into before writing.
type node struct {
	value    string
	children map[string]*node
	order    []string
}

func newNode() *node { return &node{children: map[string]*node{}} }

func (n *node) child(name string) *node {
	c, ok := n.children[name]
	if !ok {
		c = newNode()
		n.children[name] = c
		n.order = append(n.order, name)
	}
	return c
}

// listKeys are the top-level ESPHome sections that are lists of entries rather
// than a mapping. ESPHome's own schema says which; this is the short list the
// interface actually uses, and an unknown section is written as a mapping,
// which is the safer guess: a mapping written where a list belongs is a loud
// error from esphome, and a list written where a mapping belongs silently
// discards the keys.
var listKeys = map[string]bool{
	"switch":        true,
	"sensor":        true,
	"binary_sensor": true,
	"text_sensor":   true,
	"button":        true,
	"output":        true,
	"light":         true,
	"cover":         true,
	"number":        true,
	"select":        true,
	"interval":      true,
	"script":        true,
}

// Render writes the document.
//
// A path of three parts under a list section - switch.toggle.pin - means an
// entry whose id is the middle part:
//
//	switch:
//	  - id: toggle
//	    pin: 26
//
// which is how ESPHome writes a list of things each with an id, and how a
// fragment can add one setting to an entry another fragment declared.
func (d *Doc) Render() string {
	root := newNode()
	paths := make([]string, 0, len(d.values))
	for p := range d.values {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		n := root
		for _, part := range strings.Split(p, ".") {
			n = n.child(part)
		}
		n.value = d.values[p]
	}

	var b strings.Builder
	b.WriteString("# Generated by silt. Edit the fragments, not this file.\n")
	b.WriteString("#\n")
	b.WriteString("# The settings here that also appear in the Linux image's configuration -\n")
	b.WriteString("# topics, addresses, the choice of protocol - come from one statement in one\n")
	b.WriteString("# fragment, so the two sides cannot drift apart.\n\n")

	for _, name := range root.order {
		sec := root.children[name]
		if listKeys[name] && len(sec.children) > 0 {
			b.WriteString(name + ":\n")
			for _, id := range sec.order {
				entry := sec.children[id]
				b.WriteString("  - id: " + id + "\n")
				writeMapping(&b, entry, "    ")
			}
			continue
		}
		if sec.value != "" && len(sec.children) == 0 {
			fmt.Fprintf(&b, "%s: %s\n", name, scalar(sec.value))
			continue
		}
		b.WriteString(name + ":\n")
		writeMapping(&b, sec, "  ")
	}
	return b.String()
}

func writeMapping(b *strings.Builder, n *node, indent string) {
	for _, name := range n.order {
		c := n.children[name]
		if len(c.children) == 0 {
			fmt.Fprintf(b, "%s%s: %s\n", indent, name, scalar(c.value))
			continue
		}
		fmt.Fprintf(b, "%s%s:\n", indent, name)
		writeMapping(b, c, indent+"  ")
	}
}

// scalar writes a value the way YAML wants it.
//
// Numbers and booleans unquoted, everything else quoted. The quoting matters
// more than it looks: an unquoted "on" is boolean true in YAML, an unquoted
// GPIO pin name like D1 is a string, and a topic containing a colon is a
// mapping. Quoting anything that is not plainly a number or a boolean avoids
// the whole category.
func scalar(v string) string {
	if v == "" {
		return `""`
	}
	switch v {
	case "true", "false":
		return v
	}
	if _, err := strconv.ParseFloat(v, 64); err == nil {
		return v
	}
	// A duration or a pin expression such as 500ms or GPIO26 is safe bare,
	// but quoting it costs nothing and the reader loses no meaning.
	return `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
}
