// Code generated by tilegen. DO NOT EDIT.

// SMT solver boundary and SMT-LIB integration.
package solver

import "context"

type Solver interface {
	Solve(ctx context.Context, input string) (string, error)
}
